/**
 * OutlinedSpriteCache - Generates and caches outlined versions of sprites.
 *
 * For hover highlighting, instead of drawing an ellipse under entities,
 * we add a colored outline (border) to the sprite's edge pixels.
 *
 * The outline is generated by:
 * 1. Finding all "edge pixels" (non-transparent pixels with at least one transparent neighbor)
 * 2. Drawing the outline color at positions around those edge pixels
 *
 * Results are cached by (imageSrc, frameIndex, outlineColor) for performance.
 */

/** Cache key format: "imageSrc|frameX|frameY|frameW|frameH|color" */
type CacheKey = string;

/** Cached outlined canvas */
interface CachedOutline {
  canvas: HTMLCanvasElement;
  timestamp: number;
}

/** Outline thickness in pixels */
const OUTLINE_THICKNESS = 4;

/** Maximum cache size before cleanup */
const MAX_CACHE_SIZE = 200;

/** Cache lifetime in ms (5 minutes) */
const CACHE_LIFETIME_MS = 5 * 60 * 1000;

/**
 * Global cache for outlined sprites.
 */
const outlineCache: Map<CacheKey, CachedOutline> = new Map();

/**
 * Generate a cache key for an outlined sprite.
 */
function getCacheKey(
  imageSrc: string,
  srcX: number,
  srcY: number,
  srcWidth: number,
  srcHeight: number,
  outlineColor: string
): CacheKey {
  return `${imageSrc}|${srcX}|${srcY}|${srcWidth}|${srcHeight}|${outlineColor}`;
}

/**
 * Check if a pixel at (x, y) has at least one transparent neighbor.
 * Used to identify edge pixels that need outlining.
 */
function hasTransparentNeighbor(
  imageData: ImageData,
  x: number,
  y: number,
  width: number,
  height: number
): boolean {
  // Check 8 neighbors (including diagonals)
  const neighbors = [
    [-1, -1], [0, -1], [1, -1],
    [-1, 0],          [1, 0],
    [-1, 1],  [0, 1],  [1, 1],
  ];

  for (const [dx, dy] of neighbors) {
    const nx = x + dx;
    const ny = y + dy;

    // Out of bounds counts as transparent
    if (nx < 0 || nx >= width || ny < 0 || ny >= height) {
      return true;
    }

    // Check alpha of neighbor pixel
    const idx = (ny * width + nx) * 4;
    if (imageData.data[idx + 3] < 128) {
      return true;
    }
  }

  return false;
}

/**
 * Generate an outlined version of a sprite frame.
 *
 * @param image - Source image
 * @param srcX - X position of frame in source image
 * @param srcY - Y position of frame in source image
 * @param srcWidth - Width of frame
 * @param srcHeight - Height of frame
 * @param outlineColor - Color for the outline (e.g., "rgba(220, 50, 50, 0.9)")
 * @returns Canvas with the outlined sprite
 */
function generateOutlinedSprite(
  image: HTMLImageElement,
  srcX: number,
  srcY: number,
  srcWidth: number,
  srcHeight: number,
  outlineColor: string
): HTMLCanvasElement {
  // Create canvas with padding for the outline
  const padding = OUTLINE_THICKNESS;
  const canvas = document.createElement("canvas");
  canvas.width = srcWidth + padding * 2;
  canvas.height = srcHeight + padding * 2;

  const ctx = canvas.getContext("2d", { willReadFrequently: true })!;

  // Draw the original sprite frame (centered with padding)
  ctx.drawImage(
    image,
    srcX,
    srcY,
    srcWidth,
    srcHeight,
    padding,
    padding,
    srcWidth,
    srcHeight
  );

  // Get pixel data
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const { data, width, height } = imageData;

  // Find edge pixels and collect outline positions
  const outlinePositions: Array<{ x: number; y: number }> = [];

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const idx = (y * width + x) * 4;
      const alpha = data[idx + 3];

      // If this pixel is non-transparent and has a transparent neighbor, it's an edge
      if (alpha >= 128 && hasTransparentNeighbor(imageData, x, y, width, height)) {
        // Add outline positions around this edge pixel
        for (let dy = -OUTLINE_THICKNESS; dy <= OUTLINE_THICKNESS; dy++) {
          for (let dx = -OUTLINE_THICKNESS; dx <= OUTLINE_THICKNESS; dx++) {
            if (dx === 0 && dy === 0) continue;

            const ox = x + dx;
            const oy = y + dy;

            // Skip if out of bounds
            if (ox < 0 || ox >= width || oy < 0 || oy >= height) continue;

            // Skip if the outline position is already occupied by sprite pixels
            const outlineIdx = (oy * width + ox) * 4;
            if (data[outlineIdx + 3] >= 128) continue;

            outlinePositions.push({ x: ox, y: oy });
          }
        }
      }
    }
  }

  // Draw outline pixels
  ctx.fillStyle = outlineColor;
  for (const pos of outlinePositions) {
    ctx.fillRect(pos.x, pos.y, 1, 1);
  }

  // Redraw the original sprite on top (so outline is behind)
  ctx.drawImage(
    image,
    srcX,
    srcY,
    srcWidth,
    srcHeight,
    padding,
    padding,
    srcWidth,
    srcHeight
  );

  return canvas;
}

/**
 * Get or create an outlined sprite from cache.
 *
 * @param image - Source image
 * @param srcX - X position of frame in source image
 * @param srcY - Y position of frame in source image
 * @param srcWidth - Width of frame
 * @param srcHeight - Height of frame
 * @param outlineColor - Color for the outline
 * @returns Canvas with the outlined sprite, or null if image not ready
 */
export function getOutlinedSprite(
  image: HTMLImageElement,
  srcX: number,
  srcY: number,
  srcWidth: number,
  srcHeight: number,
  outlineColor: string
): HTMLCanvasElement | null {
  // Ensure image is loaded
  if (!image.complete || image.naturalWidth === 0) {
    return null;
  }

  const key = getCacheKey(image.src, srcX, srcY, srcWidth, srcHeight, outlineColor);

  // Check cache
  const cached = outlineCache.get(key);
  if (cached) {
    cached.timestamp = Date.now(); // Update last access time
    return cached.canvas;
  }

  // Generate new outlined sprite
  const canvas = generateOutlinedSprite(
    image,
    srcX,
    srcY,
    srcWidth,
    srcHeight,
    outlineColor
  );

  // Cache it
  outlineCache.set(key, {
    canvas,
    timestamp: Date.now(),
  });

  // Cleanup old entries if cache is too large
  if (outlineCache.size > MAX_CACHE_SIZE) {
    cleanupCache();
  }

  return canvas;
}

/**
 * Remove old entries from cache.
 */
function cleanupCache(): void {
  const now = Date.now();
  const toDelete: CacheKey[] = [];

  for (const [key, entry] of outlineCache) {
    if (now - entry.timestamp > CACHE_LIFETIME_MS) {
      toDelete.push(key);
    }
  }

  for (const key of toDelete) {
    outlineCache.delete(key);
  }

  // If still too large, remove oldest entries
  if (outlineCache.size > MAX_CACHE_SIZE) {
    const entries = Array.from(outlineCache.entries());
    entries.sort((a, b) => a[1].timestamp - b[1].timestamp);

    const toRemove = entries.slice(0, entries.length - MAX_CACHE_SIZE / 2);
    for (const [key] of toRemove) {
      outlineCache.delete(key);
    }
  }
}

/**
 * Outline colors for different highlight types.
 */
export const OUTLINE_COLORS = {
  ENEMY: "rgba(220, 50, 50, 0.95)",    // Red for enemies
  ALLY: "rgba(50, 200, 50, 0.95)",     // Green for allies
  SELECTED: "rgba(255, 255, 255, 0.9)", // White for selected
};

/**
 * Get the padding added by the outline (for positioning adjustments).
 */
export function getOutlinePadding(): number {
  return OUTLINE_THICKNESS;
}

/**
 * Clear the entire outline cache (useful for cleanup on level change).
 */
export function clearOutlineCache(): void {
  outlineCache.clear();
}
